### ISSUE TITLE
채팅 화면 디자인

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#17]
![image](https://github.com/DMU2024/finder-fe/assets/93248349/98277158-38a7-4c65-858d-1f56824e9519)

**Comment by b1uey0** [comment]
![chatPage01](https://github.com/DMU2024/finder-fe/assets/143199798/62928cd2-5e8d-4aad-850e-dbc25f5c86c4)
https://www.figma.com/design/4tUpbjTBf8SeAzdgHMlPFD/Finder?node-id=46-3967&t=TVjwfVVkIdpW386J-1
