### ISSUE TITLE
페이지 디자인 구성

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#2]
# Todo

- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7

**Comment by b1uey0** [comment]
현재 메인화면 디자인 完 (mapping 팝업 wireframe 작업 X)


'분실물 & 습득물 팝업' 과 '분실물 & 습득물 등록화면' wireframe 은 월요일까지 전달 드리도록 하겠습니다.
분실물 & 습득물 관련 페이지 디자인은 수요일까지 마무리 예정입니다.

제외한 마이페이지, 로그인/회원가입 등의 wireframe 역시 수요일까지 전달 드리도록 하겠습니다.

**Comment by salmontaker** [comment]
@b1uey0 디자인 수고하셨습니다! 

카카오맵 연동은 어제 완료하였고, 내일 중으로 올려주신 디자인 반영하여 스타일링 작업하겠습니다!

**Comment by salmontaker** [comment]
@b1uey0 빠른 분실물 찾기는 논의가 필요할듯 하여 제외하고 작업했습니다. 

#9 확인 부탁드립니다!
