### ISSUE TITLE
메인화면 (지도) 디자인

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#3]

**Comment by b1uey0** [comment]
![main01](https://github.com/DMU2024/finder-fe/assets/143199798/14354c3b-fde4-43be-8e4d-19a1a9dbd834)
![main02](https://github.com/DMU2024/finder-fe/assets/143199798/3b1bc92c-a1a1-4add-ae0b-070d09edde77)

# 메인화면 디자인

Pages의 Main Page(Map) 확인
https://www.figma.com/file/4tUpbjTBf8SeAzdgHMlPFD/Finder?type=design&node-id=17%3A9&mode=design&t=NV6D6kzcnBfMAEIE-1
