### ISSUE TITLE
분실물 & 습득물 팝업

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#4]

**Comment by b1uey0** [comment]
![mapping01](https://github.com/DMU2024/finder-fe/assets/143199798/dccc5a04-f342-49ea-a72e-aa0ba3d1e88b)

# 분실물 & 습득물 팝업
https://www.figma.com/file/4tUpbjTBf8SeAzdgHMlPFD/Finder?type=design&node-id=17%3A9&mode=design&t=QZU6ewMsPO691TVI-1
