### ISSUE TITLE
분실물 & 습득물 검색화면 (무한 스크롤)

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#5]

**Comment by b1uey0** [comment]
![search01](https://github.com/DMU2024/finder-fe/assets/143199798/c56728d7-57c3-424e-a152-09006f4dbf21)

# 분실물 & 습득물 검색화면
https://www.figma.com/file/4tUpbjTBf8SeAzdgHMlPFD/Finder?type=design&node-id=17%3A10&mode=design&t=NV6D6kzcnBfMAEIE-1
