### ISSUE TITLE
분실물 & 습득물 상세화면

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#6]

**Comment by b1uey0** [comment]
![Detail01](https://github.com/DMU2024/finder-fe/assets/143199798/7de24a85-60a6-4b0b-b654-86eb27b1b863)

# 분실물 & 습득물 상세화면
https://www.figma.com/file/4tUpbjTBf8SeAzdgHMlPFD/Finder?type=design&node-id=17%3A10&mode=design&t=NV6D6kzcnBfMAEIE-1

**Comment by b1uey0** [comment]
상세화면 wireframe -> 추가적인 디자인 진행 예정
