### ISSUE TITLE
분실물 & 습득물 등록화면

### ISSUE THREAD

**Issue by salmontaker** [DMU2024/finder-fe#7]

**Comment by b1uey0** [comment]
![myPage01](https://github.com/DMU2024/finder-fe/assets/143199798/e6fc0b49-cbb6-4c3a-bf57-e8bb9363e67a)
![submit01](https://github.com/DMU2024/finder-fe/assets/143199798/858f3029-de1d-40c2-a55d-de24cb0afaf7)

# 분실물 & 습득물 등록화면
https://www.figma.com/file/4tUpbjTBf8SeAzdgHMlPFD/Finder?type=design&node-id=17%3A10&mode=design&t=QZU6ewMsPO691TVI-1

erd 확인했으므로 디자인 작업 마칠 때까지 관련 내용 수정해두겠습니다.
마이페이지 작업 역시 진행 중이나, 들어갈 내용은 협의가 필요할 것으로 보입니다!
